package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.AfterType;
import cn.bdqn.mbg.model.AfterTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AfterTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int countByExample(AfterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int deleteByExample(AfterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int deleteByPrimaryKey(Integer afterTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int insert(AfterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int insertSelective(AfterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    List<AfterType> selectByExample(AfterTypeExample afterType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    AfterType selectByPrimaryKey(Integer afterTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") AfterType record, @Param("example") AfterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int updateByExample(@Param("record") AfterType record, @Param("example") AfterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int updateByPrimaryKeySelective(AfterType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Wed May 13 11:03:44 CST 2020
     */
    int updateByPrimaryKey(AfterType record);


}