package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.AuditType;
import cn.bdqn.mbg.model.AuditTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AuditTypeMapper {

    List<AuditType> selectByAuditId(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int countByExample(AuditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int deleteByExample(AuditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int deleteByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int insert(AuditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int insertSelective(AuditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    List<AuditType> selectByExample(AuditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    AuditType selectByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") AuditType record, @Param("example") AuditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int updateByExample(@Param("record") AuditType record, @Param("example") AuditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int updateByPrimaryKeySelective(AuditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    int updateByPrimaryKey(AuditType record);
}