package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.MessageType;
import cn.bdqn.mbg.model.MessageTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MessageTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int countByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insert(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insertSelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    List<MessageType> selectByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    MessageType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") MessageType record, @Param("example") MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExample(@Param("record") MessageType record, @Param("example") MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKeySelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKey(MessageType record);
}