package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.MissionType;
import cn.bdqn.mbg.model.MissionTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MissionTypeMapper {

    List<MissionType> selectTypeName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int countByExample(MissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int deleteByExample(MissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int deleteByPrimaryKey(Integer missionTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int insert(MissionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int insertSelective(MissionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    List<MissionType> selectByExample(MissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    MissionType selectByPrimaryKey(Integer missionTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") MissionType record, @Param("example") MissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int updateByExample(@Param("record") MissionType record, @Param("example") MissionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int updateByPrimaryKeySelective(MissionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    int updateByPrimaryKey(MissionType record);
}