package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.ReadMessage;
import cn.bdqn.mbg.model.ReadMessageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Mapper
@Repository
public interface ReadMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int countByExample(ReadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int deleteByExample(ReadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int deleteByPrimaryKey(Integer readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int insert(ReadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int insertSelective(ReadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    List<ReadMessage> selectByExample(ReadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    ReadMessage selectByPrimaryKey(Integer readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") ReadMessage record, @Param("example") ReadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int updateByExample(@Param("record") ReadMessage record, @Param("example") ReadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int updateByPrimaryKeySelective(ReadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    int updateByPrimaryKey(ReadMessage record);
}