package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.Sys;
import cn.bdqn.mbg.model.SysExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int countByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByPrimaryKey(Integer sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insert(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insertSelective(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    List<Sys> selectByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    Sys selectByPrimaryKey(Integer sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sys record, @Param("example") SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExample(@Param("record") Sys record, @Param("example") SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKeySelective(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKey(Sys record);
}