package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.TradePattern;
import cn.bdqn.mbg.model.TradePatternExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TradePatternMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int countByExample(TradePatternExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByExample(TradePatternExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByPrimaryKey(Integer tradePatternId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insert(TradePattern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insertSelective(TradePattern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    List<TradePattern> selectByExample(TradePatternExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    TradePattern selectByPrimaryKey(Integer tradePatternId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") TradePattern record, @Param("example") TradePatternExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExample(@Param("record") TradePattern record, @Param("example") TradePatternExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKeySelective(TradePattern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKey(TradePattern record);
}