package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.TradeType;
import cn.bdqn.mbg.model.TradeTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TradeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int countByExample(TradeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByExample(TradeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int deleteByPrimaryKey(Integer tradeTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insert(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int insertSelective(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    List<TradeType> selectByExample(TradeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    TradeType selectByPrimaryKey(Integer tradeTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") TradeType record, @Param("example") TradeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByExample(@Param("record") TradeType record, @Param("example") TradeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKeySelective(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    int updateByPrimaryKey(TradeType record);
}