package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.TrialLog;
import cn.bdqn.mbg.model.TrialLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TrialLogMapper {

    List<TrialLog> selectByAudit();

    TrialLog selectByPrimaryKey2(Integer trialId);

    List<TrialLog> selectByNotAudit(TrialLog trialLog);

    List<TrialLog> selectByAuditFinish(TrialLog trialLog);

    List<TrialLog> selectByAuditId(TrialLog trialLog);

    List<TrialLog> selectSubmit(TrialLog trialLog);

    List<TrialLog> selectByTrialLog(TrialLogExample example);

    TrialLog selectByTrialId(Integer trialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int countByExample(TrialLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int deleteByExample(TrialLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int deleteByPrimaryKey(Integer trialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int insert(TrialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int insertSelective(TrialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     * @param example
     */
    List<TrialLog> selectByExample(Integer example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    TrialLog selectByPrimaryKey(Integer trialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") TrialLog record, @Param("example") TrialLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int updateByExample(@Param("record") TrialLog record, @Param("example") TrialLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int updateByPrimaryKeySelective(TrialLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    int updateByPrimaryKey(TrialLog record);

    int updateDiary(@Param("trialId") Integer trialId, @Param("auditId") Integer auditId);
}