package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.UserStateType;
import cn.bdqn.mbg.model.UserStateTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UserStateTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int countByExample(UserStateTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int deleteByExample(UserStateTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int deleteByPrimaryKey(Integer userStId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int insert(UserStateType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int insertSelective(UserStateType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    List<UserStateType> selectByExample(UserStateTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    UserStateType selectByPrimaryKey(Integer userStId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserStateType record, @Param("example") UserStateTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int updateByExample(@Param("record") UserStateType record, @Param("example") UserStateTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int updateByPrimaryKeySelective(UserStateType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    int updateByPrimaryKey(UserStateType record);
}