package cn.bdqn.mbg.mapper;

import cn.bdqn.mbg.model.UserState;
import cn.bdqn.mbg.model.UserStateExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UserStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int countByExample(UserStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int deleteByExample(UserStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int deleteByPrimaryKey(Integer userStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int insert(UserState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int insertSelective(UserState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    List<UserState> selectByExample(UserStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    UserState selectByPrimaryKey(Integer userStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserState record, @Param("example") UserStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int updateByExample(@Param("record") UserState record, @Param("example") UserStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int updateByPrimaryKeySelective(UserState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state
     *
     * @mbggenerated Tue May 26 14:32:04 CST 2020
     */
    int updateByPrimaryKey(UserState record);
}