package cn.bdqn.mbg.model;

import java.io.Serializable;

public class AfterType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_type.after_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer afterTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_type.after_type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String afterTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_type.after_type_id
     *
     * @return the value of after_type.after_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getAfterTypeId() {
        return afterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_type.after_type_id
     *
     * @param afterTypeId the value for after_type.after_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setAfterTypeId(Integer afterTypeId) {
        this.afterTypeId = afterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_type.after_type_name
     *
     * @return the value of after_type.after_type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getAfterTypeName() {
        return afterTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_type.after_type_name
     *
     * @param afterTypeName the value for after_type.after_type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setAfterTypeName(String afterTypeName) {
        this.afterTypeName = afterTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", afterTypeId=").append(afterTypeId);
        sb.append(", afterTypeName=").append(afterTypeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}