package cn.bdqn.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AfterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public AfterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAfterIdIsNull() {
            addCriterion("after_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterIdIsNotNull() {
            addCriterion("after_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterIdEqualTo(Integer value) {
            addCriterion("after_id =", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdNotEqualTo(Integer value) {
            addCriterion("after_id <>", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdGreaterThan(Integer value) {
            addCriterion("after_id >", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_id >=", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdLessThan(Integer value) {
            addCriterion("after_id <", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdLessThanOrEqualTo(Integer value) {
            addCriterion("after_id <=", value, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdIn(List<Integer> values) {
            addCriterion("after_id in", values, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdNotIn(List<Integer> values) {
            addCriterion("after_id not in", values, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdBetween(Integer value1, Integer value2) {
            addCriterion("after_id between", value1, value2, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("after_id not between", value1, value2, "afterId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdIsNull() {
            addCriterion("after_type_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdIsNotNull() {
            addCriterion("after_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdEqualTo(Integer value) {
            addCriterion("after_type_id =", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdNotEqualTo(Integer value) {
            addCriterion("after_type_id <>", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdGreaterThan(Integer value) {
            addCriterion("after_type_id >", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_type_id >=", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdLessThan(Integer value) {
            addCriterion("after_type_id <", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("after_type_id <=", value, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdIn(List<Integer> values) {
            addCriterion("after_type_id in", values, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdNotIn(List<Integer> values) {
            addCriterion("after_type_id not in", values, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("after_type_id between", value1, value2, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("after_type_id not between", value1, value2, "afterTypeId");
            return (Criteria) this;
        }

        public Criteria andAfterStoreIsNull() {
            addCriterion("after_store is null");
            return (Criteria) this;
        }

        public Criteria andAfterStoreIsNotNull() {
            addCriterion("after_store is not null");
            return (Criteria) this;
        }

        public Criteria andAfterStoreEqualTo(Integer value) {
            addCriterion("after_store =", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreNotEqualTo(Integer value) {
            addCriterion("after_store <>", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreGreaterThan(Integer value) {
            addCriterion("after_store >", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_store >=", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreLessThan(Integer value) {
            addCriterion("after_store <", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreLessThanOrEqualTo(Integer value) {
            addCriterion("after_store <=", value, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreIn(List<Integer> values) {
            addCriterion("after_store in", values, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreNotIn(List<Integer> values) {
            addCriterion("after_store not in", values, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreBetween(Integer value1, Integer value2) {
            addCriterion("after_store between", value1, value2, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterStoreNotBetween(Integer value1, Integer value2) {
            addCriterion("after_store not between", value1, value2, "afterStore");
            return (Criteria) this;
        }

        public Criteria andAfterMissionIsNull() {
            addCriterion("after_mission is null");
            return (Criteria) this;
        }

        public Criteria andAfterMissionIsNotNull() {
            addCriterion("after_mission is not null");
            return (Criteria) this;
        }

        public Criteria andAfterMissionEqualTo(Integer value) {
            addCriterion("after_mission =", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionNotEqualTo(Integer value) {
            addCriterion("after_mission <>", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionGreaterThan(Integer value) {
            addCriterion("after_mission >", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_mission >=", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionLessThan(Integer value) {
            addCriterion("after_mission <", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionLessThanOrEqualTo(Integer value) {
            addCriterion("after_mission <=", value, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionIn(List<Integer> values) {
            addCriterion("after_mission in", values, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionNotIn(List<Integer> values) {
            addCriterion("after_mission not in", values, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionBetween(Integer value1, Integer value2) {
            addCriterion("after_mission between", value1, value2, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterMissionNotBetween(Integer value1, Integer value2) {
            addCriterion("after_mission not between", value1, value2, "afterMission");
            return (Criteria) this;
        }

        public Criteria andAfterReasonIsNull() {
            addCriterion("after_reason is null");
            return (Criteria) this;
        }

        public Criteria andAfterReasonIsNotNull() {
            addCriterion("after_reason is not null");
            return (Criteria) this;
        }

        public Criteria andAfterReasonEqualTo(String value) {
            addCriterion("after_reason =", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonNotEqualTo(String value) {
            addCriterion("after_reason <>", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonGreaterThan(String value) {
            addCriterion("after_reason >", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonGreaterThanOrEqualTo(String value) {
            addCriterion("after_reason >=", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonLessThan(String value) {
            addCriterion("after_reason <", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonLessThanOrEqualTo(String value) {
            addCriterion("after_reason <=", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonLike(String value) {
            addCriterion("after_reason like", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonNotLike(String value) {
            addCriterion("after_reason not like", value, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonIn(List<String> values) {
            addCriterion("after_reason in", values, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonNotIn(List<String> values) {
            addCriterion("after_reason not in", values, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonBetween(String value1, String value2) {
            addCriterion("after_reason between", value1, value2, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterReasonNotBetween(String value1, String value2) {
            addCriterion("after_reason not between", value1, value2, "afterReason");
            return (Criteria) this;
        }

        public Criteria andAfterPIsNull() {
            addCriterion("after_p is null");
            return (Criteria) this;
        }

        public Criteria andAfterPIsNotNull() {
            addCriterion("after_p is not null");
            return (Criteria) this;
        }

        public Criteria andAfterPEqualTo(Integer value) {
            addCriterion("after_p =", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPNotEqualTo(Integer value) {
            addCriterion("after_p <>", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPGreaterThan(Integer value) {
            addCriterion("after_p >", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_p >=", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPLessThan(Integer value) {
            addCriterion("after_p <", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPLessThanOrEqualTo(Integer value) {
            addCriterion("after_p <=", value, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPIn(List<Integer> values) {
            addCriterion("after_p in", values, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPNotIn(List<Integer> values) {
            addCriterion("after_p not in", values, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPBetween(Integer value1, Integer value2) {
            addCriterion("after_p between", value1, value2, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterPNotBetween(Integer value1, Integer value2) {
            addCriterion("after_p not between", value1, value2, "afterP");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIsNull() {
            addCriterion("after_time is null");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIsNotNull() {
            addCriterion("after_time is not null");
            return (Criteria) this;
        }

        public Criteria andAfterTimeEqualTo(Date value) {
            addCriterion("after_time =", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotEqualTo(Date value) {
            addCriterion("after_time <>", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeGreaterThan(Date value) {
            addCriterion("after_time >", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("after_time >=", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeLessThan(Date value) {
            addCriterion("after_time <", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeLessThanOrEqualTo(Date value) {
            addCriterion("after_time <=", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIn(List<Date> values) {
            addCriterion("after_time in", values, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotIn(List<Date> values) {
            addCriterion("after_time not in", values, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeBetween(Date value1, Date value2) {
            addCriterion("after_time between", value1, value2, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotBetween(Date value1, Date value2) {
            addCriterion("after_time not between", value1, value2, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterCtIsNull() {
            addCriterion("after_ct is null");
            return (Criteria) this;
        }

        public Criteria andAfterCtIsNotNull() {
            addCriterion("after_ct is not null");
            return (Criteria) this;
        }

        public Criteria andAfterCtEqualTo(Date value) {
            addCriterion("after_ct =", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtNotEqualTo(Date value) {
            addCriterion("after_ct <>", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtGreaterThan(Date value) {
            addCriterion("after_ct >", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtGreaterThanOrEqualTo(Date value) {
            addCriterion("after_ct >=", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtLessThan(Date value) {
            addCriterion("after_ct <", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtLessThanOrEqualTo(Date value) {
            addCriterion("after_ct <=", value, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtIn(List<Date> values) {
            addCriterion("after_ct in", values, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtNotIn(List<Date> values) {
            addCriterion("after_ct not in", values, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtBetween(Date value1, Date value2) {
            addCriterion("after_ct between", value1, value2, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterCtNotBetween(Date value1, Date value2) {
            addCriterion("after_ct not between", value1, value2, "afterCt");
            return (Criteria) this;
        }

        public Criteria andAfterDpIsNull() {
            addCriterion("after_dp is null");
            return (Criteria) this;
        }

        public Criteria andAfterDpIsNotNull() {
            addCriterion("after_dp is not null");
            return (Criteria) this;
        }

        public Criteria andAfterDpEqualTo(Integer value) {
            addCriterion("after_dp =", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpNotEqualTo(Integer value) {
            addCriterion("after_dp <>", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpGreaterThan(Integer value) {
            addCriterion("after_dp >", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_dp >=", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpLessThan(Integer value) {
            addCriterion("after_dp <", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpLessThanOrEqualTo(Integer value) {
            addCriterion("after_dp <=", value, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpIn(List<Integer> values) {
            addCriterion("after_dp in", values, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpNotIn(List<Integer> values) {
            addCriterion("after_dp not in", values, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpBetween(Integer value1, Integer value2) {
            addCriterion("after_dp between", value1, value2, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterDpNotBetween(Integer value1, Integer value2) {
            addCriterion("after_dp not between", value1, value2, "afterDp");
            return (Criteria) this;
        }

        public Criteria andAfterResultIsNull() {
            addCriterion("after_result is null");
            return (Criteria) this;
        }

        public Criteria andAfterResultIsNotNull() {
            addCriterion("after_result is not null");
            return (Criteria) this;
        }

        public Criteria andAfterResultEqualTo(Integer value) {
            addCriterion("after_result =", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotEqualTo(Integer value) {
            addCriterion("after_result <>", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultGreaterThan(Integer value) {
            addCriterion("after_result >", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_result >=", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultLessThan(Integer value) {
            addCriterion("after_result <", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultLessThanOrEqualTo(Integer value) {
            addCriterion("after_result <=", value, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultIn(List<Integer> values) {
            addCriterion("after_result in", values, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotIn(List<Integer> values) {
            addCriterion("after_result not in", values, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultBetween(Integer value1, Integer value2) {
            addCriterion("after_result between", value1, value2, "afterResult");
            return (Criteria) this;
        }

        public Criteria andAfterResultNotBetween(Integer value1, Integer value2) {
            addCriterion("after_result not between", value1, value2, "afterResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 03 10:06:48 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}