package cn.bdqn.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class After implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_type_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_store
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_mission
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterMission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_reason
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private String afterReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_p
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_time
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Date afterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_ct
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Date afterCt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_dp
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterDp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after.after_result
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private Integer afterResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_id
     *
     * @return the value of after.after_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterId() {
        return afterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_id
     *
     * @param afterId the value for after.after_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterId(Integer afterId) {
        this.afterId = afterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_type_id
     *
     * @return the value of after.after_type_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterTypeId() {
        return afterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_type_id
     *
     * @param afterTypeId the value for after.after_type_id
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterTypeId(Integer afterTypeId) {
        this.afterTypeId = afterTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_store
     *
     * @return the value of after.after_store
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterStore() {
        return afterStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_store
     *
     * @param afterStore the value for after.after_store
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterStore(Integer afterStore) {
        this.afterStore = afterStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_mission
     *
     * @return the value of after.after_mission
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterMission() {
        return afterMission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_mission
     *
     * @param afterMission the value for after.after_mission
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterMission(Integer afterMission) {
        this.afterMission = afterMission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_reason
     *
     * @return the value of after.after_reason
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public String getAfterReason() {
        return afterReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_reason
     *
     * @param afterReason the value for after.after_reason
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterReason(String afterReason) {
        this.afterReason = afterReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_p
     *
     * @return the value of after.after_p
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterP() {
        return afterP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_p
     *
     * @param afterP the value for after.after_p
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterP(Integer afterP) {
        this.afterP = afterP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_time
     *
     * @return the value of after.after_time
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Date getAfterTime() {
        return afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_time
     *
     * @param afterTime the value for after.after_time
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterTime(Date afterTime) {
        this.afterTime = afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_ct
     *
     * @return the value of after.after_ct
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Date getAfterCt() {
        return afterCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_ct
     *
     * @param afterCt the value for after.after_ct
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterCt(Date afterCt) {
        this.afterCt = afterCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_dp
     *
     * @return the value of after.after_dp
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterDp() {
        return afterDp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_dp
     *
     * @param afterDp the value for after.after_dp
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterDp(Integer afterDp) {
        this.afterDp = afterDp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after.after_result
     *
     * @return the value of after.after_result
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public Integer getAfterResult() {
        return afterResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after.after_result
     *
     * @param afterResult the value for after.after_result
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    public void setAfterResult(Integer afterResult) {
        this.afterResult = afterResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after
     *
     * @mbggenerated Wed Jun 03 10:06:48 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", afterId=").append(afterId);
        sb.append(", afterTypeId=").append(afterTypeId);
        sb.append(", afterStore=").append(afterStore);
        sb.append(", afterMission=").append(afterMission);
        sb.append(", afterReason=").append(afterReason);
        sb.append(", afterP=").append(afterP);
        sb.append(", afterTime=").append(afterTime);
        sb.append(", afterCt=").append(afterCt);
        sb.append(", afterDp=").append(afterDp);
        sb.append(", afterResult=").append(afterResult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}