package cn.bdqn.mbg.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AuditType implements Serializable {

    private Integer auditId;
    private String auditName;

    private String missionTypeName;
    private String missionTypePicture;
    private String missionHeadline;
    private Integer missionNo;
    private BigDecimal missionMoney;
    private String userName;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date missionSt;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date missionCt;
    private Integer trialId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_type.audit_id
     *
     * @return the value of audit_type.audit_id
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    public Integer getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_type.audit_id
     *
     * @param auditId the value for audit_type.audit_id
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_type.audit_name
     *
     * @return the value of audit_type.audit_name
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_type.audit_name
     *
     * @param auditName the value for audit_type.audit_name
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    public String getMissionTypeName() {
        return missionTypeName;
    }

    public void setMissionTypeName(String missionTypeName) {
        this.missionTypeName = missionTypeName;
    }

    public String getMissionTypePicture() {
        return missionTypePicture;
    }

    public void setMissionTypePicture(String missionTypePicture) {
        this.missionTypePicture = missionTypePicture;
    }

    public String getMissionHeadline() {
        return missionHeadline;
    }

    public void setMissionHeadline(String missionHeadline) {
        this.missionHeadline = missionHeadline;
    }

    public Integer getMissionNo() {
        return missionNo;
    }

    public void setMissionNo(Integer missionNo) {
        this.missionNo = missionNo;
    }

    public BigDecimal getMissionMoney() {
        return missionMoney;
    }

    public void setMissionMoney(BigDecimal missionMoney) {
        this.missionMoney = missionMoney;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getMissionSt() {
        return missionSt;
    }

    public void setMissionSt(Date missionSt) {
        this.missionSt = missionSt;
    }

    public Date getMissionCt() {
        return missionCt;
    }

    public void setMissionCt(Date missionCt) {
        this.missionCt = missionCt;
    }

    public Integer getTrialId() {
        return trialId;
    }

    public void setTrialId(Integer trialId) {
        this.trialId = trialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_type
     *
     * @mbggenerated Tue Jun 09 12:51:11 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", auditId=").append(auditId);
        sb.append(", auditName=").append(auditName);
        sb.append(", missionTypeName=").append(missionTypeName);
        sb.append(", missionTypePicture=").append(missionTypePicture);
        sb.append(", missionHeadline=").append(missionHeadline);
        sb.append(", missionNo=").append(missionNo);
        sb.append(", missionMoney=").append(missionMoney);
        sb.append(", userName=").append(userName);
        sb.append(", missionSt=").append(missionSt);
        sb.append(", missionCt=").append(missionCt);
        sb.append(", trialId=").append(trialId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}