package cn.bdqn.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FeedbackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public FeedbackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFeedbackIdIsNull() {
            addCriterion("feedback_id is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdIsNotNull() {
            addCriterion("feedback_id is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdEqualTo(Integer value) {
            addCriterion("feedback_id =", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdNotEqualTo(Integer value) {
            addCriterion("feedback_id <>", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdGreaterThan(Integer value) {
            addCriterion("feedback_id >", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedback_id >=", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdLessThan(Integer value) {
            addCriterion("feedback_id <", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdLessThanOrEqualTo(Integer value) {
            addCriterion("feedback_id <=", value, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdIn(List<Integer> values) {
            addCriterion("feedback_id in", values, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdNotIn(List<Integer> values) {
            addCriterion("feedback_id not in", values, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdBetween(Integer value1, Integer value2) {
            addCriterion("feedback_id between", value1, value2, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackIdNotBetween(Integer value1, Integer value2) {
            addCriterion("feedback_id not between", value1, value2, "feedbackId");
            return (Criteria) this;
        }

        public Criteria andFeedbackConIsNull() {
            addCriterion("feedback_con is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackConIsNotNull() {
            addCriterion("feedback_con is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackConEqualTo(String value) {
            addCriterion("feedback_con =", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConNotEqualTo(String value) {
            addCriterion("feedback_con <>", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConGreaterThan(String value) {
            addCriterion("feedback_con >", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConGreaterThanOrEqualTo(String value) {
            addCriterion("feedback_con >=", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConLessThan(String value) {
            addCriterion("feedback_con <", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConLessThanOrEqualTo(String value) {
            addCriterion("feedback_con <=", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConLike(String value) {
            addCriterion("feedback_con like", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConNotLike(String value) {
            addCriterion("feedback_con not like", value, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConIn(List<String> values) {
            addCriterion("feedback_con in", values, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConNotIn(List<String> values) {
            addCriterion("feedback_con not in", values, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConBetween(String value1, String value2) {
            addCriterion("feedback_con between", value1, value2, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackConNotBetween(String value1, String value2) {
            addCriterion("feedback_con not between", value1, value2, "feedbackCon");
            return (Criteria) this;
        }

        public Criteria andFeedbackPIsNull() {
            addCriterion("feedback_p is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackPIsNotNull() {
            addCriterion("feedback_p is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackPEqualTo(Integer value) {
            addCriterion("feedback_p =", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPNotEqualTo(Integer value) {
            addCriterion("feedback_p <>", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPGreaterThan(Integer value) {
            addCriterion("feedback_p >", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedback_p >=", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPLessThan(Integer value) {
            addCriterion("feedback_p <", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPLessThanOrEqualTo(Integer value) {
            addCriterion("feedback_p <=", value, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPIn(List<Integer> values) {
            addCriterion("feedback_p in", values, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPNotIn(List<Integer> values) {
            addCriterion("feedback_p not in", values, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPBetween(Integer value1, Integer value2) {
            addCriterion("feedback_p between", value1, value2, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackPNotBetween(Integer value1, Integer value2) {
            addCriterion("feedback_p not between", value1, value2, "feedbackP");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIsNull() {
            addCriterion("feedback_time is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIsNotNull() {
            addCriterion("feedback_time is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeEqualTo(Date value) {
            addCriterion("feedback_time =", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotEqualTo(Date value) {
            addCriterion("feedback_time <>", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeGreaterThan(Date value) {
            addCriterion("feedback_time >", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("feedback_time >=", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeLessThan(Date value) {
            addCriterion("feedback_time <", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeLessThanOrEqualTo(Date value) {
            addCriterion("feedback_time <=", value, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeIn(List<Date> values) {
            addCriterion("feedback_time in", values, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotIn(List<Date> values) {
            addCriterion("feedback_time not in", values, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeBetween(Date value1, Date value2) {
            addCriterion("feedback_time between", value1, value2, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackTimeNotBetween(Date value1, Date value2) {
            addCriterion("feedback_time not between", value1, value2, "feedbackTime");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateIsNull() {
            addCriterion("feedback_state is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateIsNotNull() {
            addCriterion("feedback_state is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateEqualTo(Integer value) {
            addCriterion("feedback_state =", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateNotEqualTo(Integer value) {
            addCriterion("feedback_state <>", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateGreaterThan(Integer value) {
            addCriterion("feedback_state >", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedback_state >=", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateLessThan(Integer value) {
            addCriterion("feedback_state <", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateLessThanOrEqualTo(Integer value) {
            addCriterion("feedback_state <=", value, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateIn(List<Integer> values) {
            addCriterion("feedback_state in", values, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateNotIn(List<Integer> values) {
            addCriterion("feedback_state not in", values, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateBetween(Integer value1, Integer value2) {
            addCriterion("feedback_state between", value1, value2, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackStateNotBetween(Integer value1, Integer value2) {
            addCriterion("feedback_state not between", value1, value2, "feedbackState");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpIsNull() {
            addCriterion("feedback_dp is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpIsNotNull() {
            addCriterion("feedback_dp is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpEqualTo(Integer value) {
            addCriterion("feedback_dp =", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpNotEqualTo(Integer value) {
            addCriterion("feedback_dp <>", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpGreaterThan(Integer value) {
            addCriterion("feedback_dp >", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedback_dp >=", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpLessThan(Integer value) {
            addCriterion("feedback_dp <", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpLessThanOrEqualTo(Integer value) {
            addCriterion("feedback_dp <=", value, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpIn(List<Integer> values) {
            addCriterion("feedback_dp in", values, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpNotIn(List<Integer> values) {
            addCriterion("feedback_dp not in", values, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpBetween(Integer value1, Integer value2) {
            addCriterion("feedback_dp between", value1, value2, "feedbackDp");
            return (Criteria) this;
        }

        public Criteria andFeedbackDpNotBetween(Integer value1, Integer value2) {
            addCriterion("feedback_dp not between", value1, value2, "feedbackDp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feedback
     *
     * @mbggenerated do_not_delete_during_merge Mon May 25 11:08:02 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feedback
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}