package cn.bdqn.mbg.model;

import java.io.Serializable;

public class MessageType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.type_id
     *
     * @return the value of message_type.type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.type_id
     *
     * @param typeId the value for message_type.type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.type_name
     *
     * @return the value of message_type.type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.type_name
     *
     * @param typeName the value for message_type.type_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeId=").append(typeId);
        sb.append(", typeName=").append(typeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}