package cn.bdqn.mbg.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public MissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMissionIdIsNull() {
            addCriterion("mission_id is null");
            return (Criteria) this;
        }

        public Criteria andMissionIdIsNotNull() {
            addCriterion("mission_id is not null");
            return (Criteria) this;
        }

        public Criteria andMissionIdEqualTo(Integer value) {
            addCriterion("mission_id =", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotEqualTo(Integer value) {
            addCriterion("mission_id <>", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdGreaterThan(Integer value) {
            addCriterion("mission_id >", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_id >=", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdLessThan(Integer value) {
            addCriterion("mission_id <", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("mission_id <=", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdIn(List<Integer> values) {
            addCriterion("mission_id in", values, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotIn(List<Integer> values) {
            addCriterion("mission_id not in", values, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdBetween(Integer value1, Integer value2) {
            addCriterion("mission_id between", value1, value2, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_id not between", value1, value2, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionNoIsNull() {
            addCriterion("mission_no is null");
            return (Criteria) this;
        }

        public Criteria andMissionNoIsNotNull() {
            addCriterion("mission_no is not null");
            return (Criteria) this;
        }

        public Criteria andMissionNoEqualTo(Integer value) {
            addCriterion("mission_no =", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoNotEqualTo(Integer value) {
            addCriterion("mission_no <>", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoGreaterThan(Integer value) {
            addCriterion("mission_no >", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_no >=", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoLessThan(Integer value) {
            addCriterion("mission_no <", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoLessThanOrEqualTo(Integer value) {
            addCriterion("mission_no <=", value, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoIn(List<Integer> values) {
            addCriterion("mission_no in", values, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoNotIn(List<Integer> values) {
            addCriterion("mission_no not in", values, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoBetween(Integer value1, Integer value2) {
            addCriterion("mission_no between", value1, value2, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionNoNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_no not between", value1, value2, "missionNo");
            return (Criteria) this;
        }

        public Criteria andMissionSysIsNull() {
            addCriterion("mission_sys is null");
            return (Criteria) this;
        }

        public Criteria andMissionSysIsNotNull() {
            addCriterion("mission_sys is not null");
            return (Criteria) this;
        }

        public Criteria andMissionSysEqualTo(Integer value) {
            addCriterion("mission_sys =", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysNotEqualTo(Integer value) {
            addCriterion("mission_sys <>", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysGreaterThan(Integer value) {
            addCriterion("mission_sys >", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_sys >=", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysLessThan(Integer value) {
            addCriterion("mission_sys <", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysLessThanOrEqualTo(Integer value) {
            addCriterion("mission_sys <=", value, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysIn(List<Integer> values) {
            addCriterion("mission_sys in", values, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysNotIn(List<Integer> values) {
            addCriterion("mission_sys not in", values, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysBetween(Integer value1, Integer value2) {
            addCriterion("mission_sys between", value1, value2, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionSysNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_sys not between", value1, value2, "missionSys");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIsNull() {
            addCriterion("mission_type is null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIsNotNull() {
            addCriterion("mission_type is not null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeEqualTo(Integer value) {
            addCriterion("mission_type =", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNotEqualTo(Integer value) {
            addCriterion("mission_type <>", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeGreaterThan(Integer value) {
            addCriterion("mission_type >", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_type >=", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeLessThan(Integer value) {
            addCriterion("mission_type <", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeLessThanOrEqualTo(Integer value) {
            addCriterion("mission_type <=", value, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIn(List<Integer> values) {
            addCriterion("mission_type in", values, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNotIn(List<Integer> values) {
            addCriterion("mission_type not in", values, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeBetween(Integer value1, Integer value2) {
            addCriterion("mission_type between", value1, value2, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_type not between", value1, value2, "missionType");
            return (Criteria) this;
        }

        public Criteria andMissionManaIsNull() {
            addCriterion("mission_mana is null");
            return (Criteria) this;
        }

        public Criteria andMissionManaIsNotNull() {
            addCriterion("mission_mana is not null");
            return (Criteria) this;
        }

        public Criteria andMissionManaEqualTo(Integer value) {
            addCriterion("mission_mana =", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaNotEqualTo(Integer value) {
            addCriterion("mission_mana <>", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaGreaterThan(Integer value) {
            addCriterion("mission_mana >", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_mana >=", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaLessThan(Integer value) {
            addCriterion("mission_mana <", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaLessThanOrEqualTo(Integer value) {
            addCriterion("mission_mana <=", value, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaIn(List<Integer> values) {
            addCriterion("mission_mana in", values, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaNotIn(List<Integer> values) {
            addCriterion("mission_mana not in", values, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaBetween(Integer value1, Integer value2) {
            addCriterion("mission_mana between", value1, value2, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionManaNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_mana not between", value1, value2, "missionMana");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineIsNull() {
            addCriterion("mission_headline is null");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineIsNotNull() {
            addCriterion("mission_headline is not null");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineEqualTo(String value) {
            addCriterion("mission_headline =", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineNotEqualTo(String value) {
            addCriterion("mission_headline <>", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineGreaterThan(String value) {
            addCriterion("mission_headline >", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("mission_headline >=", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineLessThan(String value) {
            addCriterion("mission_headline <", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineLessThanOrEqualTo(String value) {
            addCriterion("mission_headline <=", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineLike(String value) {
            addCriterion("mission_headline like", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineNotLike(String value) {
            addCriterion("mission_headline not like", value, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineIn(List<String> values) {
            addCriterion("mission_headline in", values, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineNotIn(List<String> values) {
            addCriterion("mission_headline not in", values, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineBetween(String value1, String value2) {
            addCriterion("mission_headline between", value1, value2, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionHeadlineNotBetween(String value1, String value2) {
            addCriterion("mission_headline not between", value1, value2, "missionHeadline");
            return (Criteria) this;
        }

        public Criteria andMissionContentIsNull() {
            addCriterion("mission_content is null");
            return (Criteria) this;
        }

        public Criteria andMissionContentIsNotNull() {
            addCriterion("mission_content is not null");
            return (Criteria) this;
        }

        public Criteria andMissionContentEqualTo(String value) {
            addCriterion("mission_content =", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentNotEqualTo(String value) {
            addCriterion("mission_content <>", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentGreaterThan(String value) {
            addCriterion("mission_content >", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentGreaterThanOrEqualTo(String value) {
            addCriterion("mission_content >=", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentLessThan(String value) {
            addCriterion("mission_content <", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentLessThanOrEqualTo(String value) {
            addCriterion("mission_content <=", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentLike(String value) {
            addCriterion("mission_content like", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentNotLike(String value) {
            addCriterion("mission_content not like", value, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentIn(List<String> values) {
            addCriterion("mission_content in", values, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentNotIn(List<String> values) {
            addCriterion("mission_content not in", values, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentBetween(String value1, String value2) {
            addCriterion("mission_content between", value1, value2, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionContentNotBetween(String value1, String value2) {
            addCriterion("mission_content not between", value1, value2, "missionContent");
            return (Criteria) this;
        }

        public Criteria andMissionStepIsNull() {
            addCriterion("mission_step is null");
            return (Criteria) this;
        }

        public Criteria andMissionStepIsNotNull() {
            addCriterion("mission_step is not null");
            return (Criteria) this;
        }

        public Criteria andMissionStepEqualTo(String value) {
            addCriterion("mission_step =", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepNotEqualTo(String value) {
            addCriterion("mission_step <>", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepGreaterThan(String value) {
            addCriterion("mission_step >", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepGreaterThanOrEqualTo(String value) {
            addCriterion("mission_step >=", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepLessThan(String value) {
            addCriterion("mission_step <", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepLessThanOrEqualTo(String value) {
            addCriterion("mission_step <=", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepLike(String value) {
            addCriterion("mission_step like", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepNotLike(String value) {
            addCriterion("mission_step not like", value, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepIn(List<String> values) {
            addCriterion("mission_step in", values, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepNotIn(List<String> values) {
            addCriterion("mission_step not in", values, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepBetween(String value1, String value2) {
            addCriterion("mission_step between", value1, value2, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStepNotBetween(String value1, String value2) {
            addCriterion("mission_step not between", value1, value2, "missionStep");
            return (Criteria) this;
        }

        public Criteria andMissionStIsNull() {
            addCriterion("mission_st is null");
            return (Criteria) this;
        }

        public Criteria andMissionStIsNotNull() {
            addCriterion("mission_st is not null");
            return (Criteria) this;
        }

        public Criteria andMissionStEqualTo(Date value) {
            addCriterion("mission_st =", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStNotEqualTo(Date value) {
            addCriterion("mission_st <>", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStGreaterThan(Date value) {
            addCriterion("mission_st >", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStGreaterThanOrEqualTo(Date value) {
            addCriterion("mission_st >=", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStLessThan(Date value) {
            addCriterion("mission_st <", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStLessThanOrEqualTo(Date value) {
            addCriterion("mission_st <=", value, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStIn(List<Date> values) {
            addCriterion("mission_st in", values, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStNotIn(List<Date> values) {
            addCriterion("mission_st not in", values, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStBetween(Date value1, Date value2) {
            addCriterion("mission_st between", value1, value2, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionStNotBetween(Date value1, Date value2) {
            addCriterion("mission_st not between", value1, value2, "missionSt");
            return (Criteria) this;
        }

        public Criteria andMissionCtIsNull() {
            addCriterion("mission_ct is null");
            return (Criteria) this;
        }

        public Criteria andMissionCtIsNotNull() {
            addCriterion("mission_ct is not null");
            return (Criteria) this;
        }

        public Criteria andMissionCtEqualTo(Date value) {
            addCriterion("mission_ct =", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtNotEqualTo(Date value) {
            addCriterion("mission_ct <>", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtGreaterThan(Date value) {
            addCriterion("mission_ct >", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtGreaterThanOrEqualTo(Date value) {
            addCriterion("mission_ct >=", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtLessThan(Date value) {
            addCriterion("mission_ct <", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtLessThanOrEqualTo(Date value) {
            addCriterion("mission_ct <=", value, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtIn(List<Date> values) {
            addCriterion("mission_ct in", values, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtNotIn(List<Date> values) {
            addCriterion("mission_ct not in", values, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtBetween(Date value1, Date value2) {
            addCriterion("mission_ct between", value1, value2, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionCtNotBetween(Date value1, Date value2) {
            addCriterion("mission_ct not between", value1, value2, "missionCt");
            return (Criteria) this;
        }

        public Criteria andMissionNumIsNull() {
            addCriterion("mission_num is null");
            return (Criteria) this;
        }

        public Criteria andMissionNumIsNotNull() {
            addCriterion("mission_num is not null");
            return (Criteria) this;
        }

        public Criteria andMissionNumEqualTo(Integer value) {
            addCriterion("mission_num =", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumNotEqualTo(Integer value) {
            addCriterion("mission_num <>", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumGreaterThan(Integer value) {
            addCriterion("mission_num >", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_num >=", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumLessThan(Integer value) {
            addCriterion("mission_num <", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumLessThanOrEqualTo(Integer value) {
            addCriterion("mission_num <=", value, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumIn(List<Integer> values) {
            addCriterion("mission_num in", values, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumNotIn(List<Integer> values) {
            addCriterion("mission_num not in", values, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumBetween(Integer value1, Integer value2) {
            addCriterion("mission_num between", value1, value2, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionNumNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_num not between", value1, value2, "missionNum");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyIsNull() {
            addCriterion("mission_money is null");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyIsNotNull() {
            addCriterion("mission_money is not null");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyEqualTo(BigDecimal value) {
            addCriterion("mission_money =", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyNotEqualTo(BigDecimal value) {
            addCriterion("mission_money <>", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyGreaterThan(BigDecimal value) {
            addCriterion("mission_money >", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mission_money >=", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyLessThan(BigDecimal value) {
            addCriterion("mission_money <", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mission_money <=", value, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyIn(List<BigDecimal> values) {
            addCriterion("mission_money in", values, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyNotIn(List<BigDecimal> values) {
            addCriterion("mission_money not in", values, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mission_money between", value1, value2, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mission_money not between", value1, value2, "missionMoney");
            return (Criteria) this;
        }

        public Criteria andMissionAllIsNull() {
            addCriterion("mission_all is null");
            return (Criteria) this;
        }

        public Criteria andMissionAllIsNotNull() {
            addCriterion("mission_all is not null");
            return (Criteria) this;
        }

        public Criteria andMissionAllEqualTo(BigDecimal value) {
            addCriterion("mission_all =", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllNotEqualTo(BigDecimal value) {
            addCriterion("mission_all <>", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllGreaterThan(BigDecimal value) {
            addCriterion("mission_all >", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mission_all >=", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllLessThan(BigDecimal value) {
            addCriterion("mission_all <", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mission_all <=", value, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllIn(List<BigDecimal> values) {
            addCriterion("mission_all in", values, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllNotIn(List<BigDecimal> values) {
            addCriterion("mission_all not in", values, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mission_all between", value1, value2, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionAllNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mission_all not between", value1, value2, "missionAll");
            return (Criteria) this;
        }

        public Criteria andMissionLinkIsNull() {
            addCriterion("mission_link is null");
            return (Criteria) this;
        }

        public Criteria andMissionLinkIsNotNull() {
            addCriterion("mission_link is not null");
            return (Criteria) this;
        }

        public Criteria andMissionLinkEqualTo(String value) {
            addCriterion("mission_link =", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkNotEqualTo(String value) {
            addCriterion("mission_link <>", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkGreaterThan(String value) {
            addCriterion("mission_link >", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkGreaterThanOrEqualTo(String value) {
            addCriterion("mission_link >=", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkLessThan(String value) {
            addCriterion("mission_link <", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkLessThanOrEqualTo(String value) {
            addCriterion("mission_link <=", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkLike(String value) {
            addCriterion("mission_link like", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkNotLike(String value) {
            addCriterion("mission_link not like", value, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkIn(List<String> values) {
            addCriterion("mission_link in", values, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkNotIn(List<String> values) {
            addCriterion("mission_link not in", values, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkBetween(String value1, String value2) {
            addCriterion("mission_link between", value1, value2, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionLinkNotBetween(String value1, String value2) {
            addCriterion("mission_link not between", value1, value2, "missionLink");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyIsNull() {
            addCriterion("mission_verify is null");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyIsNotNull() {
            addCriterion("mission_verify is not null");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyEqualTo(String value) {
            addCriterion("mission_verify =", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyNotEqualTo(String value) {
            addCriterion("mission_verify <>", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyGreaterThan(String value) {
            addCriterion("mission_verify >", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyGreaterThanOrEqualTo(String value) {
            addCriterion("mission_verify >=", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyLessThan(String value) {
            addCriterion("mission_verify <", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyLessThanOrEqualTo(String value) {
            addCriterion("mission_verify <=", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyLike(String value) {
            addCriterion("mission_verify like", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyNotLike(String value) {
            addCriterion("mission_verify not like", value, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyIn(List<String> values) {
            addCriterion("mission_verify in", values, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyNotIn(List<String> values) {
            addCriterion("mission_verify not in", values, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyBetween(String value1, String value2) {
            addCriterion("mission_verify between", value1, value2, "missionVerify");
            return (Criteria) this;
        }

        public Criteria andMissionVerifyNotBetween(String value1, String value2) {
            addCriterion("mission_verify not between", value1, value2, "missionVerify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 10:14:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbggenerated Thu Jun 04 10:14:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}