package cn.bdqn.mbg.model;

import java.io.Serializable;

public class MissionType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_type.mission_type_id
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    private Integer missionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_type.mission_type_name
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    private String missionTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_type.mission_type_picture
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    private String missionTypePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_type.mission_type_id
     *
     * @return the value of mission_type.mission_type_id
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public Integer getMissionTypeId() {
        return missionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_type.mission_type_id
     *
     * @param missionTypeId the value for mission_type.mission_type_id
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void setMissionTypeId(Integer missionTypeId) {
        this.missionTypeId = missionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_type.mission_type_name
     *
     * @return the value of mission_type.mission_type_name
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public String getMissionTypeName() {
        return missionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_type.mission_type_name
     *
     * @param missionTypeName the value for mission_type.mission_type_name
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void setMissionTypeName(String missionTypeName) {
        this.missionTypeName = missionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_type.mission_type_picture
     *
     * @return the value of mission_type.mission_type_picture
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public String getMissionTypePicture() {
        return missionTypePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_type.mission_type_picture
     *
     * @param missionTypePicture the value for mission_type.mission_type_picture
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void setMissionTypePicture(String missionTypePicture) {
        this.missionTypePicture = missionTypePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", missionTypeId=").append(missionTypeId);
        sb.append(", missionTypeName=").append(missionTypeName);
        sb.append(", missionTypePicture=").append(missionTypePicture);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}