package cn.bdqn.mbg.model;

import java.util.ArrayList;
import java.util.List;

public class MissionTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public MissionTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMissionTypeIdIsNull() {
            addCriterion("mission_type_id is null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdIsNotNull() {
            addCriterion("mission_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdEqualTo(Integer value) {
            addCriterion("mission_type_id =", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdNotEqualTo(Integer value) {
            addCriterion("mission_type_id <>", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdGreaterThan(Integer value) {
            addCriterion("mission_type_id >", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_type_id >=", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdLessThan(Integer value) {
            addCriterion("mission_type_id <", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("mission_type_id <=", value, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdIn(List<Integer> values) {
            addCriterion("mission_type_id in", values, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdNotIn(List<Integer> values) {
            addCriterion("mission_type_id not in", values, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("mission_type_id between", value1, value2, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_type_id not between", value1, value2, "missionTypeId");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameIsNull() {
            addCriterion("mission_type_name is null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameIsNotNull() {
            addCriterion("mission_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameEqualTo(String value) {
            addCriterion("mission_type_name =", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameNotEqualTo(String value) {
            addCriterion("mission_type_name <>", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameGreaterThan(String value) {
            addCriterion("mission_type_name >", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("mission_type_name >=", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameLessThan(String value) {
            addCriterion("mission_type_name <", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameLessThanOrEqualTo(String value) {
            addCriterion("mission_type_name <=", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameLike(String value) {
            addCriterion("mission_type_name like", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameNotLike(String value) {
            addCriterion("mission_type_name not like", value, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameIn(List<String> values) {
            addCriterion("mission_type_name in", values, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameNotIn(List<String> values) {
            addCriterion("mission_type_name not in", values, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameBetween(String value1, String value2) {
            addCriterion("mission_type_name between", value1, value2, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypeNameNotBetween(String value1, String value2) {
            addCriterion("mission_type_name not between", value1, value2, "missionTypeName");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureIsNull() {
            addCriterion("mission_type_picture is null");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureIsNotNull() {
            addCriterion("mission_type_picture is not null");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureEqualTo(String value) {
            addCriterion("mission_type_picture =", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureNotEqualTo(String value) {
            addCriterion("mission_type_picture <>", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureGreaterThan(String value) {
            addCriterion("mission_type_picture >", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureGreaterThanOrEqualTo(String value) {
            addCriterion("mission_type_picture >=", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureLessThan(String value) {
            addCriterion("mission_type_picture <", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureLessThanOrEqualTo(String value) {
            addCriterion("mission_type_picture <=", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureLike(String value) {
            addCriterion("mission_type_picture like", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureNotLike(String value) {
            addCriterion("mission_type_picture not like", value, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureIn(List<String> values) {
            addCriterion("mission_type_picture in", values, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureNotIn(List<String> values) {
            addCriterion("mission_type_picture not in", values, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureBetween(String value1, String value2) {
            addCriterion("mission_type_picture between", value1, value2, "missionTypePicture");
            return (Criteria) this;
        }

        public Criteria andMissionTypePictureNotBetween(String value1, String value2) {
            addCriterion("mission_type_picture not between", value1, value2, "missionTypePicture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission_type
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 04 10:12:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission_type
     *
     * @mbggenerated Thu Jun 04 10:12:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}