package cn.bdqn.mbg.model;

import java.io.Serializable;

public class ReadMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_message.read_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    private Integer readId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_message.read_send_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    private Integer readSendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_message.read_p
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    private Integer readP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_message.read_id
     *
     * @return the value of read_message.read_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public Integer getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_message.read_id
     *
     * @param readId the value for read_message.read_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public void setReadId(Integer readId) {
        this.readId = readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_message.read_send_id
     *
     * @return the value of read_message.read_send_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public Integer getReadSendId() {
        return readSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_message.read_send_id
     *
     * @param readSendId the value for read_message.read_send_id
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public void setReadSendId(Integer readSendId) {
        this.readSendId = readSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_message.read_p
     *
     * @return the value of read_message.read_p
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public Integer getReadP() {
        return readP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_message.read_p
     *
     * @param readP the value for read_message.read_p
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    public void setReadP(Integer readP) {
        this.readP = readP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_message
     *
     * @mbggenerated Wed May 13 11:03:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", readId=").append(readId);
        sb.append(", readSendId=").append(readSendId);
        sb.append(", readP=").append(readP);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}