package cn.bdqn.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class SendMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer sendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer sendTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_little
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String sendLittle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_content
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String sendContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer sendP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_message.send_user
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer sendUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table send_message
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_id
     *
     * @return the value of send_message.send_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_id
     *
     * @param sendId the value for send_message.send_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendId(Integer sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_type_id
     *
     * @return the value of send_message.send_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getSendTypeId() {
        return sendTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_type_id
     *
     * @param sendTypeId the value for send_message.send_type_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendTypeId(Integer sendTypeId) {
        this.sendTypeId = sendTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_time
     *
     * @return the value of send_message.send_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_time
     *
     * @param sendTime the value for send_message.send_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_little
     *
     * @return the value of send_message.send_little
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getSendLittle() {
        return sendLittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_little
     *
     * @param sendLittle the value for send_message.send_little
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendLittle(String sendLittle) {
        this.sendLittle = sendLittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_content
     *
     * @return the value of send_message.send_content
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getSendContent() {
        return sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_content
     *
     * @param sendContent the value for send_message.send_content
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_p
     *
     * @return the value of send_message.send_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getSendP() {
        return sendP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_p
     *
     * @param sendP the value for send_message.send_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendP(Integer sendP) {
        this.sendP = sendP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_message.send_user
     *
     * @return the value of send_message.send_user
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getSendUser() {
        return sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_message.send_user
     *
     * @param sendUser the value for send_message.send_user
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setSendUser(Integer sendUser) {
        this.sendUser = sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_message
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sendId=").append(sendId);
        sb.append(", sendTypeId=").append(sendTypeId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", sendLittle=").append(sendLittle);
        sb.append(", sendContent=").append(sendContent);
        sb.append(", sendP=").append(sendP);
        sb.append(", sendUser=").append(sendUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}