package cn.bdqn.mbg.model;

import java.io.Serializable;

public class Store implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_no
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer storeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.user_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_ex
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer storeEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table store
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_id
     *
     * @return the value of store.store_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_id
     *
     * @param storeId the value for store.store_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_no
     *
     * @return the value of store.store_no
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getStoreNo() {
        return storeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_no
     *
     * @param storeNo the value for store.store_no
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setStoreNo(Integer storeNo) {
        this.storeNo = storeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_name
     *
     * @return the value of store.store_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_name
     *
     * @param storeName the value for store.store_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.user_id
     *
     * @return the value of store.user_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.user_id
     *
     * @param userId the value for store.user_id
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_ex
     *
     * @return the value of store.store_ex
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getStoreEx() {
        return storeEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_ex
     *
     * @param storeEx the value for store.store_ex
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setStoreEx(Integer storeEx) {
        this.storeEx = storeEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", storeId=").append(storeId);
        sb.append(", storeNo=").append(storeNo);
        sb.append(", storeName=").append(storeName);
        sb.append(", userId=").append(userId);
        sb.append(", storeEx=").append(storeEx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}