package cn.bdqn.mbg.model;

import java.util.ArrayList;
import java.util.List;

public class TradePatternExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public TradePatternExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTradePatternIdIsNull() {
            addCriterion("trade_pattern_ID is null");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdIsNotNull() {
            addCriterion("trade_pattern_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdEqualTo(Integer value) {
            addCriterion("trade_pattern_ID =", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdNotEqualTo(Integer value) {
            addCriterion("trade_pattern_ID <>", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdGreaterThan(Integer value) {
            addCriterion("trade_pattern_ID >", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("trade_pattern_ID >=", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdLessThan(Integer value) {
            addCriterion("trade_pattern_ID <", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdLessThanOrEqualTo(Integer value) {
            addCriterion("trade_pattern_ID <=", value, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdIn(List<Integer> values) {
            addCriterion("trade_pattern_ID in", values, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdNotIn(List<Integer> values) {
            addCriterion("trade_pattern_ID not in", values, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdBetween(Integer value1, Integer value2) {
            addCriterion("trade_pattern_ID between", value1, value2, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternIdNotBetween(Integer value1, Integer value2) {
            addCriterion("trade_pattern_ID not between", value1, value2, "tradePatternId");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameIsNull() {
            addCriterion("trade_pattern_name is null");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameIsNotNull() {
            addCriterion("trade_pattern_name is not null");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameEqualTo(String value) {
            addCriterion("trade_pattern_name =", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameNotEqualTo(String value) {
            addCriterion("trade_pattern_name <>", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameGreaterThan(String value) {
            addCriterion("trade_pattern_name >", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameGreaterThanOrEqualTo(String value) {
            addCriterion("trade_pattern_name >=", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameLessThan(String value) {
            addCriterion("trade_pattern_name <", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameLessThanOrEqualTo(String value) {
            addCriterion("trade_pattern_name <=", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameLike(String value) {
            addCriterion("trade_pattern_name like", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameNotLike(String value) {
            addCriterion("trade_pattern_name not like", value, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameIn(List<String> values) {
            addCriterion("trade_pattern_name in", values, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameNotIn(List<String> values) {
            addCriterion("trade_pattern_name not in", values, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameBetween(String value1, String value2) {
            addCriterion("trade_pattern_name between", value1, value2, "tradePatternName");
            return (Criteria) this;
        }

        public Criteria andTradePatternNameNotBetween(String value1, String value2) {
            addCriterion("trade_pattern_name not between", value1, value2, "tradePatternName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_pattern
     *
     * @mbggenerated do_not_delete_during_merge Mon May 25 11:08:02 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}