package cn.bdqn.mbg.model;

import java.io.Serializable;

public class TradePattern implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pattern.trade_pattern_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer tradePatternId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pattern.trade_pattern_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private String tradePatternName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pattern.trade_pattern_ID
     *
     * @return the value of trade_pattern.trade_pattern_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTradePatternId() {
        return tradePatternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pattern.trade_pattern_ID
     *
     * @param tradePatternId the value for trade_pattern.trade_pattern_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradePatternId(Integer tradePatternId) {
        this.tradePatternId = tradePatternId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pattern.trade_pattern_name
     *
     * @return the value of trade_pattern.trade_pattern_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public String getTradePatternName() {
        return tradePatternName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pattern.trade_pattern_name
     *
     * @param tradePatternName the value for trade_pattern.trade_pattern_name
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradePatternName(String tradePatternName) {
        this.tradePatternName = tradePatternName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tradePatternId=").append(tradePatternId);
        sb.append(", tradePatternName=").append(tradePatternName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}