package cn.bdqn.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Trade implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer tradePattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_money
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private BigDecimal tradeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Integer tradeP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private Date tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_ID
     *
     * @return the value of trade.trade_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_ID
     *
     * @param tradeId the value for trade.trade_ID
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_type
     *
     * @return the value of trade.trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_type
     *
     * @param tradeType the value for trade.trade_type
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_pattern
     *
     * @return the value of trade.trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTradePattern() {
        return tradePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_pattern
     *
     * @param tradePattern the value for trade.trade_pattern
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradePattern(Integer tradePattern) {
        this.tradePattern = tradePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_money
     *
     * @return the value of trade.trade_money
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public BigDecimal getTradeMoney() {
        return tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_money
     *
     * @param tradeMoney the value for trade.trade_money
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradeMoney(BigDecimal tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_p
     *
     * @return the value of trade.trade_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Integer getTradeP() {
        return tradeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_p
     *
     * @param tradeP the value for trade.trade_p
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradeP(Integer tradeP) {
        this.tradeP = tradeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_time
     *
     * @return the value of trade.trade_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_time
     *
     * @param tradeTime the value for trade.trade_time
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Mon May 25 11:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tradeId=").append(tradeId);
        sb.append(", tradeType=").append(tradeType);
        sb.append(", tradePattern=").append(tradePattern);
        sb.append(", tradeMoney=").append(tradeMoney);
        sb.append(", tradeP=").append(tradeP);
        sb.append(", tradeTime=").append(tradeTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}