package cn.bdqn.mbg.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TrialLog implements Serializable {

    private Integer trialId;
    private Integer missionId;
    private Integer userId;
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date trialT;
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date trialCt;
    private Integer auditId;
    private String trialText;
    private String trialS;
    private Integer missionTypeId;

    private String missionTypeName;
    private String missionTypePicture;
    private String missionHeadline;
    private Integer missionNo;
    private BigDecimal missionMoney;
    private Integer missionNum;
    private String userName;
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date missionCt;
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date missionSt;
    private String userHead;
    private String missionText;
    private String missionVerify;
    private String missionPattern;
    private String auditName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Date getTrialCt() {
        return trialCt;
    }

    public void setTrialCt(Date trialCt) {
        this.trialCt = trialCt;
    }

    public Integer getMissionTypeId() {
        return missionTypeId;
    }

    public void setMissionTypeId(Integer missionTypeId) {
        this.missionTypeId = missionTypeId;
    }

    public Date getMissionCt() {
        return missionCt;
    }

    public void setMissionCt(Date missionCt) {
        this.missionCt = missionCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.trial_id
     *
     * @return the value of trial_log.trial_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public Integer getTrialId() {
        return trialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.trial_id
     *
     * @param trialId the value for trial_log.trial_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setTrialId(Integer trialId) {
        this.trialId = trialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.mission_id
     *
     * @return the value of trial_log.mission_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public Integer getMissionId() {
        return missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.mission_id
     *
     * @param missionId the value for trial_log.mission_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.user_id
     *
     * @return the value of trial_log.user_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.user_id
     *
     * @param userId the value for trial_log.user_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.trial_t
     *
     * @return the value of trial_log.trial_t
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public Date getTrialT() {
        return trialT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.trial_t
     *
     * @param trialT the value for trial_log.trial_t
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setTrialT(Date trialT) {
        this.trialT = trialT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.audit_id
     *
     * @return the value of trial_log.audit_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public Integer getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.audit_id
     *
     * @param auditId the value for trial_log.audit_id
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trial_log.trial_text
     *
     * @return the value of trial_log.trial_text
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public String getTrialText() {
        return trialText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trial_log.trial_text
     *
     * @param trialText the value for trial_log.trial_text
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    public void setTrialText(String trialText) {
        this.trialText = trialText;
    }

    public String getMissionTypeName() {
        return missionTypeName;
    }

    public void setMissionTypeName(String missionTypeName) {
        this.missionTypeName = missionTypeName;
    }

    public String getMissionTypePicture() {
        return missionTypePicture;
    }

    public void setMissionTypePicture(String missionTypePicture) {
        this.missionTypePicture = missionTypePicture;
    }

    public String getMissionHeadline() {
        return missionHeadline;
    }

    public void setMissionHeadline(String missionHeadline) {
        this.missionHeadline = missionHeadline;
    }

    public Integer getMissionNo() {
        return missionNo;
    }

    public void setMissionNo(Integer missionNo) {
        this.missionNo = missionNo;
    }

    public BigDecimal getMissionMoney() {
        return missionMoney;
    }

    public void setMissionMoney(BigDecimal missionMoney) {
        this.missionMoney = missionMoney;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getMissionSt() {
        return missionSt;
    }

    public void setMissionSt(Date missionSt) {
        this.missionSt = missionSt;
    }

    public String getUserHead() {
        return userHead;
    }

    public void setUserHead(String userHead) {
        this.userHead = userHead;
    }

    public String getMissionText() {
        return missionText;
    }

    public void setMissionText(String missionText) {
        this.missionText = missionText;
    }

    public String getMissionVerify() {
        return missionVerify;
    }

    public void setMissionVerify(String missionVerify) {
        this.missionVerify = missionVerify;
    }

    public String getMissionPattern() {
        return missionPattern;
    }

    public void setMissionPattern(String missionPattern) {
        this.missionPattern = missionPattern;
    }

    public String getTrialS() {
        return trialS;
    }

    public void setTrialS(String trialS) {
        this.trialS = trialS;
    }

    public String getAuditName() {
        return auditName;
    }

    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    public Integer getMissionNum() {
        return missionNum;
    }

    public void setMissionNum(Integer missionNum) {
        this.missionNum = missionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trial_log
     *
     * @mbggenerated Sat Jun 06 15:49:01 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trialId=").append(trialId);
        sb.append(", missionId=").append(missionId);
        sb.append(", userId=").append(userId);
        sb.append(", trialT=").append(trialT);
        sb.append(", auditId=").append(auditId);
        sb.append(", trialText=").append(trialText);
        sb.append(", missionTypeName=").append(missionTypeName);
        sb.append(", missionPattern=").append(missionPattern);
        sb.append(", missionTypePicture=").append(missionTypePicture);
        sb.append(", missionHeadline=").append(missionHeadline);
        sb.append(", missionNum=").append(missionNum);
        sb.append(", missionNo=").append(missionNo);
        sb.append(", missionMoney=").append(missionMoney);
        sb.append(", missionText=").append(missionText);
        sb.append(", missionVerify=").append(missionVerify);
        sb.append(", userName=").append(userName);
        sb.append(", userHead=").append(userHead);
        sb.append(", missionCt=").append(missionCt);
        sb.append(", missionSt=").append(missionSt);
        sb.append(", trialS=").append(trialS);
        sb.append(", trialCt=").append(trialCt);
        sb.append(", missionTypeId=").append(missionTypeId);
        sb.append(", auditName=").append(auditName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}