package cn.bdqn.mbg.model;

import java.util.ArrayList;
import java.util.List;

public class UserStateTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public UserStateTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserStIdIsNull() {
            addCriterion("user_st_id is null");
            return (Criteria) this;
        }

        public Criteria andUserStIdIsNotNull() {
            addCriterion("user_st_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserStIdEqualTo(Integer value) {
            addCriterion("user_st_id =", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdNotEqualTo(Integer value) {
            addCriterion("user_st_id <>", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdGreaterThan(Integer value) {
            addCriterion("user_st_id >", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_st_id >=", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdLessThan(Integer value) {
            addCriterion("user_st_id <", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_st_id <=", value, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdIn(List<Integer> values) {
            addCriterion("user_st_id in", values, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdNotIn(List<Integer> values) {
            addCriterion("user_st_id not in", values, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdBetween(Integer value1, Integer value2) {
            addCriterion("user_st_id between", value1, value2, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_st_id not between", value1, value2, "userStId");
            return (Criteria) this;
        }

        public Criteria andUserStNameIsNull() {
            addCriterion("user_st_name is null");
            return (Criteria) this;
        }

        public Criteria andUserStNameIsNotNull() {
            addCriterion("user_st_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserStNameEqualTo(String value) {
            addCriterion("user_st_name =", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameNotEqualTo(String value) {
            addCriterion("user_st_name <>", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameGreaterThan(String value) {
            addCriterion("user_st_name >", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_st_name >=", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameLessThan(String value) {
            addCriterion("user_st_name <", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameLessThanOrEqualTo(String value) {
            addCriterion("user_st_name <=", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameLike(String value) {
            addCriterion("user_st_name like", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameNotLike(String value) {
            addCriterion("user_st_name not like", value, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameIn(List<String> values) {
            addCriterion("user_st_name in", values, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameNotIn(List<String> values) {
            addCriterion("user_st_name not in", values, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameBetween(String value1, String value2) {
            addCriterion("user_st_name between", value1, value2, "userStName");
            return (Criteria) this;
        }

        public Criteria andUserStNameNotBetween(String value1, String value2) {
            addCriterion("user_st_name not between", value1, value2, "userStName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_state_type
     *
     * @mbggenerated do_not_delete_during_merge Tue May 26 14:30:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_state_type
     *
     * @mbggenerated Tue May 26 14:30:45 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}