package cn.bdqn.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_username
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Integer userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pwd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_head
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_real_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id_card
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userIdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_num
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private String userNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_create
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Date userCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sf
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private BigDecimal userSf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_balance
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private BigDecimal userBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_wd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private BigDecimal userWd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_ex
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Integer userEx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_state
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_username
     *
     * @return the value of user.user_username
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Integer getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_username
     *
     * @param userUsername the value for user.user_username
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserUsername(Integer userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pwd
     *
     * @return the value of user.user_pwd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pwd
     *
     * @param userPwd the value for user.user_pwd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_head
     *
     * @return the value of user.user_head
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_head
     *
     * @param userHead the value for user.user_head
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_real_name
     *
     * @return the value of user.user_real_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_real_name
     *
     * @param userRealName the value for user.user_real_name
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id_card
     *
     * @return the value of user.user_id_card
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id_card
     *
     * @param userIdCard the value for user.user_id_card
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_num
     *
     * @return the value of user.user_num
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_num
     *
     * @param userNum the value for user.user_num
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_create
     *
     * @return the value of user.user_create
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Date getUserCreate() {
        return userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_create
     *
     * @param userCreate the value for user.user_create
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserCreate(Date userCreate) {
        this.userCreate = userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sf
     *
     * @return the value of user.user_sf
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public BigDecimal getUserSf() {
        return userSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sf
     *
     * @param userSf the value for user.user_sf
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserSf(BigDecimal userSf) {
        this.userSf = userSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_balance
     *
     * @return the value of user.user_balance
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public BigDecimal getUserBalance() {
        return userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_balance
     *
     * @param userBalance the value for user.user_balance
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserBalance(BigDecimal userBalance) {
        this.userBalance = userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_wd
     *
     * @return the value of user.user_wd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public BigDecimal getUserWd() {
        return userWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_wd
     *
     * @param userWd the value for user.user_wd
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserWd(BigDecimal userWd) {
        this.userWd = userWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_ex
     *
     * @return the value of user.user_ex
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Integer getUserEx() {
        return userEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_ex
     *
     * @param userEx the value for user.user_ex
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserEx(Integer userEx) {
        this.userEx = userEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_state
     *
     * @return the value of user.user_state
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_state
     *
     * @param userState the value for user.user_state
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 08 10:33:54 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userUsername=").append(userUsername);
        sb.append(", userPwd=").append(userPwd);
        sb.append(", userHead=").append(userHead);
        sb.append(", userType=").append(userType);
        sb.append(", userRealName=").append(userRealName);
        sb.append(", userIdCard=").append(userIdCard);
        sb.append(", userNum=").append(userNum);
        sb.append(", userCreate=").append(userCreate);
        sb.append(", userSf=").append(userSf);
        sb.append(", userBalance=").append(userBalance);
        sb.append(", userWd=").append(userWd);
        sb.append(", userEx=").append(userEx);
        sb.append(", userState=").append(userState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}